### ISSUE TITLE
Upgrade to vega-lite 3

### ISSUE THREAD

**Issue by meetamit** [observablehq/vega#12]
Are you open to upgrading this module's vega-lite to version 3.0? For me specifically, it would be nice to be able to use the newly-added Boxplot mark. However, perhaps it's not time yet, because vega-lite is still versioned as release candidate (-rc6).

**Comment by domoritz** [comment]
You can already use Vega-Embed. It's a drop in replacement for the observable package and comes with themes, tooltips, and links to the editor and to download the visualization. 

Check out https://beta.observablehq.com/@domoritz/hello-vega-embed

**Comment by meetamit** [comment]
Thanks for the tip @domoritz

I've switched to Vega-Embed, and indeed it continued to work essentially the same as with @observablehq/vega, except that Vega-Embed's actions menu button appeared (by default) after the switch.

**Comment by domoritz** [comment]
Yeah, you can turn it off if you don't like it but continue to get themes and tooltips.
