### ISSUE TITLE
Vega wrapper

### ISSUE THREAD

**Issue by domoritz** [observablehq/vega#3]
It would be nice to have a wrapper for pure Vega as well. Would it make more sense to have a separate repo or could this be combined with the Vega-Lite wrapper?

**Comment by mbostock** [comment]
I think if you’re not using Vega-Lite, then you’d prefer to avoid loading it, so I think a separate npm package would make sense. They could certainly live in the same GitHub repository (monorepo), though.

In the long run, a convenience method built-in to Vega and Vega-Lite would ideally subsume the need for an Observable wrapper. 😁

**Comment by domoritz** [comment]
We do have [vega-embed](https://github.com/vega/vega-embed) as a convenience wrapper but it does expect an element to be passed in. It does provide some other cool functionality like automatically switching between Vega and Vega-Lite and links to the source and the editor.
